### ISSUE TITLE
Crashes when sending SMS message

### ISSUE THREAD

**Issue by julianfairfax** [you-apps/ConnectYou#319]
### Steps to reproduce

1. Send an SMS message

### Expected behavior

SMS message should be sent and saved

### Actual behavior

SMS message is sent, sometimes saved, sometimes not, but the app always crashes after

### Connect You version

8.0

### Android version

Android 14

### Other details

I have two SIMs, but changing which SIM the SMS message is sent with doesn't make a difference (I didn't actually try sending one with the second SIM, only changing back and forth, since I don't want to get any charges from my testing).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Crash log?

**Comment by julianfairfax** [comment]
```
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231105.003/2023111500:user/release-keys
package: com.bnyro.contacts:26
process: com.bnyro.contacts
processUptime: 7137 + 198 ms
installer: com.android.packageinstaller

java.lang.IllegalStateException: 
   FocusRequester is not initialized. Here are some possible fixes:

   1. Remember the FocusRequester: val focusRequester = remember { FocusRequester() }
   2. Did you forget to add a Modifier.focusRequester() ?
   3. Are you attempting to request focus during composition? Focus requests should be made in
   response to some event. Eg Modifier.clickable { focusRequester.requestFocus() }

	at n5.i2.y(SourceFile:456)
	at androidx.compose.foundation.h$b.g0(SourceFile:13)
	at p.e1$a.i(SourceFile:134)
	at r6.a.u(Unknown Source:8)
	at f0.o0.c(Unknown Source:82)
	at h7.j.q(SourceFile:138)
	at h7.j.F(SourceFile:45)
	at h7.j.u(SourceFile:17)
	at f1.q0.k1(SourceFile:51)
	at f1.q0.P(Unknown Source:30)
	at androidx.compose.foundation.a.P(SourceFile:7)
	at f1.l.f(SourceFile:174)
	at f1.l.f(SourceFile:153)
	at f1.l.f(SourceFile:153)
	at f1.l.f(SourceFile:153)
	at f1.h.b(SourceFile:40)
	at f1.e0.a(SourceFile:164)
	at androidx.compose.ui.platform.AndroidComposeView.R(SourceFile:79)
	at androidx.compose.ui.platform.AndroidComposeView.G(SourceFile:224)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:88)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1904)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:919)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448)
	at android.view.View.dispatchPointerEvent(View.java:15919)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7021)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6815)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6229)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6417)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6474)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9211)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9162)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9131)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9337)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: m7.g: [androidx.compose.ui.platform.m2@6c622a7, f0.f@515d354, z1{Cancelling}@7a6c2fd, e1@e184bf2]

```

**Comment by Bnyro** [comment]
Thanks for the logs!
