### ISSUE TITLE
unparsable date made by Android without a year

### ISSUE THREAD

**Issue by apprehensions** [you-apps/ConnectYou#406]
### Steps to reproduce

Step 1. Make a contact and add a date *without* a year
Step 2. Export contacts or attempt to see the contact

### Expected behavior

Able to export contacts or see contact properly

### Actual behavior

App crashed when exporting, and showing weirdly formatted date

```
FATAL EXCEPTION: main
Process: com.bnyro.contacts, PID: 2474
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1297977771, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/... flg=0x43 }} to activity {com.bnyro.contacts/com.bnyro.contacts.ui.activities.MainActivity}: java.text.ParseException: Unparseable date: "--12-19"
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5815)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5854)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:69)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.text.ParseException: Unparseable date: "--12-19"
	at java.text.DateFormat.parse(DateFormat.java:393)
	at a6.b.a(Unknown Source:7)
	at a6.b0.j(SourceFile:574)
	at a6.f.a(SourceFile:30)
	at w5.a.f(SourceFile:26)
	at y5.l$n.g0(SourceFile:12)
	at c.b.a(Unknown Source:8)
	at androidx.activity.result.d.a(SourceFile:45)
	at androidx.activity.ComponentActivity.onActivityResult(Unknown Source:2)
	at android.app.Activity.internalDispatchActivityResult(Activity.java:9358)
	at android.app.Activity.dispatchActivityResult(Activity.java:9342)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5807)
	... 14 more
```

### Connect You version

9.0

### Android version

Android 14

### Other details

Android Contacts app:
![20240904_200806](https://github.com/user-attachments/assets/89bbf97f-5cfc-4d35-b50a-549c8c92f735)
Contact You:
![20240904_200915](https://github.com/user-attachments/assets/77639272-06fb-4e58-98d1-2e67b0ed120f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by apprehensions** [comment]
Thanks!
